[package]
name = "nickel"
version = "0.1.0"
authors = ["Nicl team"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Programmable configuration files."
edition = "2018"

[[bin]]
name = "nickel"
path = "src/bin/nickel.rs"
bench = false

[lib]
bench = false

[features]
default = ["markdown", "repl"]
markdown = ["termimad"]
repl = ["rustyline", "rustyline-derive", "ansi_term"]
repl-wasm = ["wasm-bindgen", "js-sys", "serde_repr"]

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
lalrpop-util = "0.19.6"
regex = "0.2.1"
simple-counter = "0.1.0"
codespan = "0.11"
codespan-reporting = "0.11"
logos = "0.12.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
serde_yaml = "0.8.15"
toml = "0.5.8"
structopt = "0.3"
void = "1"
sha-1 = "0.9.3"
sha2 = "0.9.3"
md-5 = "0.9.1"
directories = "4.0.1"

termimad = { version = "0.16.2", optional = true }
ansi_term = { version = "0.12", optional = true }

rustyline = { version = "7.1.0", optional = true}
rustyline-derive = { version = "0.4.0", optional = true }

wasm-bindgen = { version = "=0.2.74", optional = true, features = ["serde-serialize"] }
js-sys = { version = "0.3", optional = true }
serde_repr = { version = "0.1", optional = true }

[dev-dependencies]
pretty_assertions = "0.5.1"
assert_matches = "1.4.0"
criterion = "0.3"
pprof = { version = "0.4.4", features = ["criterion", "flamegraph"] }
utilities = {path = "utilities"}

[workspace]
members = [
    ".",
    "lsp/nls",
    "fmt"
]

# Enable this to use flamegraphs
# [profile.release]
# debug = true

[[bench]]
name = "numeric"
harness = false

[[bench]]
name = "functions"
harness = false

[[bench]]
name = "lists"
harness = false

# [[bench]]
# name = "records"
# harness = false

[[bench]]
name = "serialization"
harness = false
