plugins:
  - path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"

yarnPath: .yarn/releases/yarn-3.3.0.cjs

# We import it in /flake.nix so we don't need yarn-plugin-nixify to generate a ./default.nix file
# See https://github.com/stephank/yarn-plugin-nixify#settings
generateDefaultNix: false
